  - job_name: nginx-access
    pipeline_stages:
    - regex:
        expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<timestamp>.*)\] "(?P<action>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status_code>[\d]+) (?P<body_bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"?'
    - timestamp:
          source: timestamp
          format: "02/Jan/2006:15:04:05 -0700"
    - labels:
        action:
        status_code:
    static_configs:
     - targets:
       - localhost
       labels:
        job: ngnix-access
        __path__:  /var/log/nginx/localhost.access_log

  - job_name: nginx-error
    pipeline_stages:
    - regex:
        expression: '^(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>[^\]]+)\] (?P<message>.*)$'
    - timestamp:
          source: timestamp
          format: "2006/01/02 15:04:05"
    - labels:
        level:
    static_configs:
     - targets:
       - localhost
       labels:
        job: ngnix-error
        __path__:  /var/log/nginx/{localhost.error,error}_log

